"""Fix EmailAttachment model.

Revision ID: deffbec94147
Revises: cc1fb6b21dc7
Create Date: 2026-04-22 05:45:13.102115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'deffbec94147'
down_revision: Union[str, Sequence[str], None] = 'cc1fb6b21dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_email_attachment_webhook_email_id_attachment_id', 'email_attachment', ['webhook', 'email_id', 'attachment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email_attachment_webhook_email_id_attachment_id', 'email_attachment', type_='unique')
    # ### end Alembic commands ###
